# Generated by Django 5.1.7 on 2025-03-20 02:13

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("date", models.DateField()),
                ("total_miles", models.FloatField()),
                ("total_mileage", models.FloatField()),
                ("remarks", models.TextField(blank=True)),
                ("driver_signature", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "dropoff_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("current_cycle_hours", models.FloatField()),
                ("total_distance", models.FloatField(blank=True, null=True)),
                ("total_duration", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DutyStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("off-duty", "Off Duty"),
                            ("sleeper", "Sleeper Berth"),
                            ("driving", "Driving"),
                            ("on-duty", "On Duty (Not Driving)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_statuses",
                        to="api_v1.dailylog",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel Stop"),
                            ("rest_break", "30-Minute Break"),
                            ("mandatory_rest", "10-Hour Rest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("duration", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="api_v1.route",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="route",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="api_v1.trip",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to="api_v1.trip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together={("trip", "date")},
        ),
    ]
