# Generated by Django 5.1.7 on 2025-03-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0003_add_status_description_to_duty_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="current_location_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="dropoff_location_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="pickup_location_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
